spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dealer
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  application:
    name: spring-authentication
  jackson:
    serialization:
      fail-on-empty-beans: false